// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package weichhart.georg.communication;

public final class PerformativeMessages {
  private PerformativeMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Weichhart.Georg.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Weichhart.Georg.Message.PerformativeType performative = 1;</code>
     * @return The enum numeric value on the wire for performative.
     */
    int getPerformativeValue();
    /**
     * <code>.Weichhart.Georg.Message.PerformativeType performative = 1;</code>
     * @return The performative.
     */
    weichhart.georg.communication.PerformativeMessages.Message.PerformativeType getPerformative();

    /**
     * <code>string txt = 2;</code>
     * @return The txt.
     */
    java.lang.String getTxt();
    /**
     * <code>string txt = 2;</code>
     * @return The bytes for txt.
     */
    com.google.protobuf.ByteString
        getTxtBytes();

    /**
     * <code>string subject = 3;</code>
     * @return The subject.
     */
    java.lang.String getSubject();
    /**
     * <code>string subject = 3;</code>
     * @return The bytes for subject.
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    /**
     * <code>string source = 4;</code>
     * @return The source.
     */
    java.lang.String getSource();
    /**
     * <code>string source = 4;</code>
     * @return The bytes for source.
     */
    com.google.protobuf.ByteString
        getSourceBytes();
  }
  /**
   * Protobuf type {@code Weichhart.Georg.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Weichhart.Georg.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      performative_ = 0;
      txt_ = "";
      subject_ = "";
      source_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              performative_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              txt_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              subject_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              source_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return weichhart.georg.communication.PerformativeMessages.internal_static_Weichhart_Georg_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return weichhart.georg.communication.PerformativeMessages.internal_static_Weichhart_Georg_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              weichhart.georg.communication.PerformativeMessages.Message.class, weichhart.georg.communication.PerformativeMessages.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code Weichhart.Georg.Message.PerformativeType}
     */
    public enum PerformativeType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>INFOM = 1;</code>
       */
      INFOM(1),
      /**
       * <code>INFORM_IF = 2;</code>
       */
      INFORM_IF(2),
      /**
       * <code>REQUEST = 3;</code>
       */
      REQUEST(3),
      /**
       * <code>REQUEST_WHEN = 4;</code>
       */
      REQUEST_WHEN(4),
      /**
       * <code>REQUEST_WHENEVER = 5;</code>
       */
      REQUEST_WHENEVER(5),
      /**
       * <code>QUERY = 6;</code>
       */
      QUERY(6),
      /**
       * <code>QUERY_IF = 7;</code>
       */
      QUERY_IF(7),
      /**
       * <code>AGREE = 8;</code>
       */
      AGREE(8),
      /**
       * <code>CONFIRM = 9;</code>
       */
      CONFIRM(9),
      /**
       * <code>DISCONFIRM = 10;</code>
       */
      DISCONFIRM(10),
      /**
       * <code>SUBSCRIBE = 18;</code>
       */
      SUBSCRIBE(18),
      /**
       * <code>UNSUBSCRIBE = 19;</code>
       */
      UNSUBSCRIBE(19),
      /**
       * <code>CALL_FOR_PROPOSAL = 20;</code>
       */
      CALL_FOR_PROPOSAL(20),
      /**
       * <code>PROPOSE = 21;</code>
       */
      PROPOSE(21),
      /**
       * <code>ACCEPT_PROPOSAL = 22;</code>
       */
      ACCEPT_PROPOSAL(22),
      /**
       * <code>REJECT_PROPOSAL = 23;</code>
       */
      REJECT_PROPOSAL(23),
      /**
       * <code>CANCEL = 30;</code>
       */
      CANCEL(30),
      /**
       * <code>REFUSE = 31;</code>
       */
      REFUSE(31),
      /**
       * <code>NOT_UNDERSTOOD = 32;</code>
       */
      NOT_UNDERSTOOD(32),
      /**
       * <code>FAILURE = 33;</code>
       */
      FAILURE(33),
      /**
       * <code>WARN = 34;</code>
       */
      WARN(34),
      /**
       * <code>ERROR = 35;</code>
       */
      ERROR(35),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>INFOM = 1;</code>
       */
      public static final int INFOM_VALUE = 1;
      /**
       * <code>INFORM_IF = 2;</code>
       */
      public static final int INFORM_IF_VALUE = 2;
      /**
       * <code>REQUEST = 3;</code>
       */
      public static final int REQUEST_VALUE = 3;
      /**
       * <code>REQUEST_WHEN = 4;</code>
       */
      public static final int REQUEST_WHEN_VALUE = 4;
      /**
       * <code>REQUEST_WHENEVER = 5;</code>
       */
      public static final int REQUEST_WHENEVER_VALUE = 5;
      /**
       * <code>QUERY = 6;</code>
       */
      public static final int QUERY_VALUE = 6;
      /**
       * <code>QUERY_IF = 7;</code>
       */
      public static final int QUERY_IF_VALUE = 7;
      /**
       * <code>AGREE = 8;</code>
       */
      public static final int AGREE_VALUE = 8;
      /**
       * <code>CONFIRM = 9;</code>
       */
      public static final int CONFIRM_VALUE = 9;
      /**
       * <code>DISCONFIRM = 10;</code>
       */
      public static final int DISCONFIRM_VALUE = 10;
      /**
       * <code>SUBSCRIBE = 18;</code>
       */
      public static final int SUBSCRIBE_VALUE = 18;
      /**
       * <code>UNSUBSCRIBE = 19;</code>
       */
      public static final int UNSUBSCRIBE_VALUE = 19;
      /**
       * <code>CALL_FOR_PROPOSAL = 20;</code>
       */
      public static final int CALL_FOR_PROPOSAL_VALUE = 20;
      /**
       * <code>PROPOSE = 21;</code>
       */
      public static final int PROPOSE_VALUE = 21;
      /**
       * <code>ACCEPT_PROPOSAL = 22;</code>
       */
      public static final int ACCEPT_PROPOSAL_VALUE = 22;
      /**
       * <code>REJECT_PROPOSAL = 23;</code>
       */
      public static final int REJECT_PROPOSAL_VALUE = 23;
      /**
       * <code>CANCEL = 30;</code>
       */
      public static final int CANCEL_VALUE = 30;
      /**
       * <code>REFUSE = 31;</code>
       */
      public static final int REFUSE_VALUE = 31;
      /**
       * <code>NOT_UNDERSTOOD = 32;</code>
       */
      public static final int NOT_UNDERSTOOD_VALUE = 32;
      /**
       * <code>FAILURE = 33;</code>
       */
      public static final int FAILURE_VALUE = 33;
      /**
       * <code>WARN = 34;</code>
       */
      public static final int WARN_VALUE = 34;
      /**
       * <code>ERROR = 35;</code>
       */
      public static final int ERROR_VALUE = 35;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PerformativeType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static PerformativeType forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return INFOM;
          case 2: return INFORM_IF;
          case 3: return REQUEST;
          case 4: return REQUEST_WHEN;
          case 5: return REQUEST_WHENEVER;
          case 6: return QUERY;
          case 7: return QUERY_IF;
          case 8: return AGREE;
          case 9: return CONFIRM;
          case 10: return DISCONFIRM;
          case 18: return SUBSCRIBE;
          case 19: return UNSUBSCRIBE;
          case 20: return CALL_FOR_PROPOSAL;
          case 21: return PROPOSE;
          case 22: return ACCEPT_PROPOSAL;
          case 23: return REJECT_PROPOSAL;
          case 30: return CANCEL;
          case 31: return REFUSE;
          case 32: return NOT_UNDERSTOOD;
          case 33: return FAILURE;
          case 34: return WARN;
          case 35: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PerformativeType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PerformativeType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PerformativeType>() {
              public PerformativeType findValueByNumber(int number) {
                return PerformativeType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return weichhart.georg.communication.PerformativeMessages.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final PerformativeType[] VALUES = values();

      public static PerformativeType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PerformativeType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Weichhart.Georg.Message.PerformativeType)
    }

    public static final int PERFORMATIVE_FIELD_NUMBER = 1;
    private int performative_;
    /**
     * <code>.Weichhart.Georg.Message.PerformativeType performative = 1;</code>
     * @return The enum numeric value on the wire for performative.
     */
    public int getPerformativeValue() {
      return performative_;
    }
    /**
     * <code>.Weichhart.Georg.Message.PerformativeType performative = 1;</code>
     * @return The performative.
     */
    public weichhart.georg.communication.PerformativeMessages.Message.PerformativeType getPerformative() {
      @SuppressWarnings("deprecation")
      weichhart.georg.communication.PerformativeMessages.Message.PerformativeType result = weichhart.georg.communication.PerformativeMessages.Message.PerformativeType.valueOf(performative_);
      return result == null ? weichhart.georg.communication.PerformativeMessages.Message.PerformativeType.UNRECOGNIZED : result;
    }

    public static final int TXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object txt_;
    /**
     * <code>string txt = 2;</code>
     * @return The txt.
     */
    public java.lang.String getTxt() {
      java.lang.Object ref = txt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txt_ = s;
        return s;
      }
    }
    /**
     * <code>string txt = 2;</code>
     * @return The bytes for txt.
     */
    public com.google.protobuf.ByteString
        getTxtBytes() {
      java.lang.Object ref = txt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_FIELD_NUMBER = 3;
    private volatile java.lang.Object subject_;
    /**
     * <code>string subject = 3;</code>
     * @return The subject.
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      }
    }
    /**
     * <code>string subject = 3;</code>
     * @return The bytes for subject.
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_FIELD_NUMBER = 4;
    private volatile java.lang.Object source_;
    /**
     * <code>string source = 4;</code>
     * @return The source.
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      }
    }
    /**
     * <code>string source = 4;</code>
     * @return The bytes for source.
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (performative_ != weichhart.georg.communication.PerformativeMessages.Message.PerformativeType.UNKNOWN.getNumber()) {
        output.writeEnum(1, performative_);
      }
      if (!getTxtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, txt_);
      }
      if (!getSubjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subject_);
      }
      if (!getSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, source_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (performative_ != weichhart.georg.communication.PerformativeMessages.Message.PerformativeType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, performative_);
      }
      if (!getTxtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, txt_);
      }
      if (!getSubjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subject_);
      }
      if (!getSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, source_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof weichhart.georg.communication.PerformativeMessages.Message)) {
        return super.equals(obj);
      }
      weichhart.georg.communication.PerformativeMessages.Message other = (weichhart.georg.communication.PerformativeMessages.Message) obj;

      if (performative_ != other.performative_) return false;
      if (!getTxt()
          .equals(other.getTxt())) return false;
      if (!getSubject()
          .equals(other.getSubject())) return false;
      if (!getSource()
          .equals(other.getSource())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PERFORMATIVE_FIELD_NUMBER;
      hash = (53 * hash) + performative_;
      hash = (37 * hash) + TXT_FIELD_NUMBER;
      hash = (53 * hash) + getTxt().hashCode();
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static weichhart.georg.communication.PerformativeMessages.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weichhart.georg.communication.PerformativeMessages.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weichhart.georg.communication.PerformativeMessages.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weichhart.georg.communication.PerformativeMessages.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weichhart.georg.communication.PerformativeMessages.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weichhart.georg.communication.PerformativeMessages.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weichhart.georg.communication.PerformativeMessages.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weichhart.georg.communication.PerformativeMessages.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static weichhart.georg.communication.PerformativeMessages.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static weichhart.georg.communication.PerformativeMessages.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static weichhart.georg.communication.PerformativeMessages.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weichhart.georg.communication.PerformativeMessages.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(weichhart.georg.communication.PerformativeMessages.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Weichhart.Georg.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Weichhart.Georg.Message)
        weichhart.georg.communication.PerformativeMessages.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return weichhart.georg.communication.PerformativeMessages.internal_static_Weichhart_Georg_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return weichhart.georg.communication.PerformativeMessages.internal_static_Weichhart_Georg_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                weichhart.georg.communication.PerformativeMessages.Message.class, weichhart.georg.communication.PerformativeMessages.Message.Builder.class);
      }

      // Construct using weichhart.georg.communication.PerformativeMessages.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        performative_ = 0;

        txt_ = "";

        subject_ = "";

        source_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return weichhart.georg.communication.PerformativeMessages.internal_static_Weichhart_Georg_Message_descriptor;
      }

      @java.lang.Override
      public weichhart.georg.communication.PerformativeMessages.Message getDefaultInstanceForType() {
        return weichhart.georg.communication.PerformativeMessages.Message.getDefaultInstance();
      }

      @java.lang.Override
      public weichhart.georg.communication.PerformativeMessages.Message build() {
        weichhart.georg.communication.PerformativeMessages.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public weichhart.georg.communication.PerformativeMessages.Message buildPartial() {
        weichhart.georg.communication.PerformativeMessages.Message result = new weichhart.georg.communication.PerformativeMessages.Message(this);
        result.performative_ = performative_;
        result.txt_ = txt_;
        result.subject_ = subject_;
        result.source_ = source_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof weichhart.georg.communication.PerformativeMessages.Message) {
          return mergeFrom((weichhart.georg.communication.PerformativeMessages.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(weichhart.georg.communication.PerformativeMessages.Message other) {
        if (other == weichhart.georg.communication.PerformativeMessages.Message.getDefaultInstance()) return this;
        if (other.performative_ != 0) {
          setPerformativeValue(other.getPerformativeValue());
        }
        if (!other.getTxt().isEmpty()) {
          txt_ = other.txt_;
          onChanged();
        }
        if (!other.getSubject().isEmpty()) {
          subject_ = other.subject_;
          onChanged();
        }
        if (!other.getSource().isEmpty()) {
          source_ = other.source_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        weichhart.georg.communication.PerformativeMessages.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (weichhart.georg.communication.PerformativeMessages.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int performative_ = 0;
      /**
       * <code>.Weichhart.Georg.Message.PerformativeType performative = 1;</code>
       * @return The enum numeric value on the wire for performative.
       */
      public int getPerformativeValue() {
        return performative_;
      }
      /**
       * <code>.Weichhart.Georg.Message.PerformativeType performative = 1;</code>
       * @param value The enum numeric value on the wire for performative to set.
       * @return This builder for chaining.
       */
      public Builder setPerformativeValue(int value) {
        performative_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Weichhart.Georg.Message.PerformativeType performative = 1;</code>
       * @return The performative.
       */
      public weichhart.georg.communication.PerformativeMessages.Message.PerformativeType getPerformative() {
        @SuppressWarnings("deprecation")
        weichhart.georg.communication.PerformativeMessages.Message.PerformativeType result = weichhart.georg.communication.PerformativeMessages.Message.PerformativeType.valueOf(performative_);
        return result == null ? weichhart.georg.communication.PerformativeMessages.Message.PerformativeType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Weichhart.Georg.Message.PerformativeType performative = 1;</code>
       * @param value The performative to set.
       * @return This builder for chaining.
       */
      public Builder setPerformative(weichhart.georg.communication.PerformativeMessages.Message.PerformativeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        performative_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Weichhart.Georg.Message.PerformativeType performative = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPerformative() {
        
        performative_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object txt_ = "";
      /**
       * <code>string txt = 2;</code>
       * @return The txt.
       */
      public java.lang.String getTxt() {
        java.lang.Object ref = txt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string txt = 2;</code>
       * @return The bytes for txt.
       */
      public com.google.protobuf.ByteString
          getTxtBytes() {
        java.lang.Object ref = txt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string txt = 2;</code>
       * @param value The txt to set.
       * @return This builder for chaining.
       */
      public Builder setTxt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string txt = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxt() {
        
        txt_ = getDefaultInstance().getTxt();
        onChanged();
        return this;
      }
      /**
       * <code>string txt = 2;</code>
       * @param value The bytes for txt to set.
       * @return This builder for chaining.
       */
      public Builder setTxtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subject_ = "";
      /**
       * <code>string subject = 3;</code>
       * @return The subject.
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subject = 3;</code>
       * @return The bytes for subject.
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subject = 3;</code>
       * @param value The subject to set.
       * @return This builder for chaining.
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subject = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubject() {
        
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <code>string subject = 3;</code>
       * @param value The bytes for subject to set.
       * @return This builder for chaining.
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subject_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>string source = 4;</code>
       * @return The source.
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string source = 4;</code>
       * @return The bytes for source.
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string source = 4;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string source = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>string source = 4;</code>
       * @param value The bytes for source to set.
       * @return This builder for chaining.
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        source_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Weichhart.Georg.Message)
    }

    // @@protoc_insertion_point(class_scope:Weichhart.Georg.Message)
    private static final weichhart.georg.communication.PerformativeMessages.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new weichhart.georg.communication.PerformativeMessages.Message();
    }

    public static weichhart.georg.communication.PerformativeMessages.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public weichhart.georg.communication.PerformativeMessages.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Weichhart_Georg_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Weichhart_Georg_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\017Weichhart.Georg\"\346\003\n\007Mes" +
      "sage\022?\n\014performative\030\001 \001(\0162).Weichhart.G" +
      "eorg.Message.PerformativeType\022\013\n\003txt\030\002 \001" +
      "(\t\022\017\n\007subject\030\003 \001(\t\022\016\n\006source\030\004 \001(\t\"\353\002\n\020" +
      "PerformativeType\022\013\n\007UNKNOWN\020\000\022\t\n\005INFOM\020\001" +
      "\022\r\n\tINFORM_IF\020\002\022\013\n\007REQUEST\020\003\022\020\n\014REQUEST_" +
      "WHEN\020\004\022\024\n\020REQUEST_WHENEVER\020\005\022\t\n\005QUERY\020\006\022" +
      "\014\n\010QUERY_IF\020\007\022\t\n\005AGREE\020\010\022\013\n\007CONFIRM\020\t\022\016\n" +
      "\nDISCONFIRM\020\n\022\r\n\tSUBSCRIBE\020\022\022\017\n\013UNSUBSCR" +
      "IBE\020\023\022\025\n\021CALL_FOR_PROPOSAL\020\024\022\013\n\007PROPOSE\020" +
      "\025\022\023\n\017ACCEPT_PROPOSAL\020\026\022\023\n\017REJECT_PROPOSA" +
      "L\020\027\022\n\n\006CANCEL\020\036\022\n\n\006REFUSE\020\037\022\022\n\016NOT_UNDER" +
      "STOOD\020 \022\013\n\007FAILURE\020!\022\010\n\004WARN\020\"\022\t\n\005ERROR\020" +
      "#B5\n\035weichhart.georg.communicationB\024Perf" +
      "ormativeMessagesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Weichhart_Georg_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Weichhart_Georg_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Weichhart_Georg_Message_descriptor,
        new java.lang.String[] { "Performative", "Txt", "Subject", "Source", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
